// Pure HMAC sign/verify for the admin session cookie.
// Extracted from src/lib/admin-auth.ts so that Next.js middleware/proxy
// can verify the cookie value without pulling in next/headers (which
// the proxy must not use — proxy should only touch req.cookies).
//
// The cookie value format is `<nonce>.<hex-hmac-sha256(nonce, secret)>`.
// Nonce is generated by mintAdminCookie and is hex-only, so the only
// `.` in the string is the separator between nonce and mac.

import crypto from "crypto";

export function sign(value: string, secret: string): string {
  const mac = crypto.createHmac("sha256", secret).update(value).digest("hex");
  return `${value}.${mac}`;
}

export function verify(signed: string, secret: string): string | null {
  const idx = signed.lastIndexOf(".");
  if (idx <= 0) return null;
  const value = signed.slice(0, idx);
  const mac = signed.slice(idx + 1);
  const expected = crypto.createHmac("sha256", secret).update(value).digest("hex");
  if (mac.length !== expected.length) return null;
  try {
    if (!crypto.timingSafeEqual(Buffer.from(mac, "hex"), Buffer.from(expected, "hex"))) {
      return null;
    }
  } catch {
    return null;
  }
  return value;
}
